CREATE TABLE C32.C32_DOCUMENT (
	AUDIT_MESSAGE_ID INT NOT NULL AUTO_INCREMENT,
	CREATE_DATE date,
	DOCUMENT blob,	
	PATIENT_ID	varchar(255),
	DOCUMENT_PATIENT_ID varchar(255),
	Primary key (AUDIT_MESSAGE_ID)
);

ALTER TABLE C32.C32_DOCUMENT
ADD INDEX `PATIENT_ID` (`PATIENT_ID` ASC);

CREATE TABLE C32.HIBERNATE_SEQUENCE (
	NEXT_VAL bigint(20) NOT NULL,
	Primary key (NEXT_VAL)
);

insert into C32.HIBERNATE_SEQUENCE values(1);