//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.13 at 09:33:26 PM PDT 
//


package org.osehra.das.common.rest.url;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.osehra.das.common.rest.url package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.osehra.das.common.rest.url
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UriInfo }
     * 
     */
    public UriInfo createUriInfo() {
        return new UriInfo();
    }

    /**
     * Create an instance of {@link MultiValuedMap.Entry }
     * 
     */
    public MultiValuedMap.Entry createMultiValuedMapEntry() {
        return new MultiValuedMap.Entry();
    }

    /**
     * Create an instance of {@link MultiValuedMap }
     * 
     */
    public MultiValuedMap createMultiValuedMap() {
        return new MultiValuedMap();
    }

}
