//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.13 at 09:33:26 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://org/osehra/das/common/uri", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.osehra.das.common.rest.url;
