//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.13 at 09:33:26 PM PDT 
//


package org.osehra.das.common.rest.url;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pathParameters" type="{http://org/osehra/das/common/uri}multiValuedMap"/>
 *         &lt;element name="queryParameters" type="{http://org/osehra/das/common/uri}multiValuedMap"/>
 *         &lt;element name="baseUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="absolutePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pathParameters",
    "queryParameters",
    "baseUri",
    "requestUri",
    "absolutePath",
    "path"
})
@XmlRootElement(name = "uriInfo")
public class UriInfo {

    @XmlElement(required = true)
    protected MultiValuedMap pathParameters;
    @XmlElement(required = true)
    protected MultiValuedMap queryParameters;
    @XmlElement(required = true)
    protected String baseUri;
    @XmlElement(required = true)
    protected String requestUri;
    @XmlElement(required = true)
    protected String absolutePath;
    @XmlElement(required = true)
    protected String path;

    /**
     * Gets the value of the pathParameters property.
     * 
     * @return
     *     possible object is
     *     {@link MultiValuedMap }
     *     
     */
    public MultiValuedMap getPathParameters() {
        return pathParameters;
    }

    /**
     * Sets the value of the pathParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiValuedMap }
     *     
     */
    public void setPathParameters(MultiValuedMap value) {
        this.pathParameters = value;
    }

    /**
     * Gets the value of the queryParameters property.
     * 
     * @return
     *     possible object is
     *     {@link MultiValuedMap }
     *     
     */
    public MultiValuedMap getQueryParameters() {
        return queryParameters;
    }

    /**
     * Sets the value of the queryParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiValuedMap }
     *     
     */
    public void setQueryParameters(MultiValuedMap value) {
        this.queryParameters = value;
    }

    /**
     * Gets the value of the baseUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUri() {
        return baseUri;
    }

    /**
     * Sets the value of the baseUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUri(String value) {
        this.baseUri = value;
    }

    /**
     * Gets the value of the requestUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * Sets the value of the requestUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestUri(String value) {
        this.requestUri = value;
    }

    /**
     * Gets the value of the absolutePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbsolutePath() {
        return absolutePath;
    }

    /**
     * Sets the value of the absolutePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbsolutePath(String value) {
        this.absolutePath = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
